theme: jekyll-theme-minimal

title: Stephen Ott # your name (or website title) here
logo: "images/PersonalPhoto2.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Undergraduate Software Engineer
  <br><br>
  I'm looking for opportunities to further my skill set, and at the end of the day, I want my work to matter by helping people
  <br><br>
  <a class="button" href="mailto:email@email.de">Email Me</a>
  <br><br>
  <a class="button" href="www.linkedin.com/in/stephen-ott-8104981b6">View My Linkedin Profile/a>

google_analytics: UA-148879698-1 # your Google Analytics tracking ID here
