theme: jekyll-theme-minimal

title: Stephen Ott # your name (or website title) here
logo: "images/PersonalPhoto2.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Undergraduate Software Engineer
  <br><br>
  Computer science is more than just an academic pursuit; 
  it is something for which I genuinely yearn for more knowledge.
  <br><br>
  [Click me](mailto:stott@ucdavis.edu){: .btn}
  <button onclick="window.location.href = 'mailto:stott@ucdavis.edu';">Email Me</button>
  

google_analytics: UA-148879698-1 # your Google Analytics tracking ID here
