title: Stephen Ott
author: Stephen Ott
email: stephenott531@gmail.com

theme: jekyll-theme-hacker

plugins:
  - jekyll-relative-links

relative_links:
  - enabled: true
  - collections: true
  
include:
  - index.md
  - contact.md
